language: python
install:
  - "python setup.py develop"
  - "pip install -r requirements-dev.txt --use-mirrors"
  - "pip install coveralls --use-mirrors"
python:
  - 2.7
  - 3.4
script: "nosetests --with-coverage --cover-package=mixcloud"
after_success:
  coveralls
